# Local testing can be done by using 'bundle exec jekyll serve'.
# - Site settings {{ site.* }}

title: Greathorn Games
email: hello@greathorn.games

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://greathorn.games" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
  - LICENSE