# Socials
- platform: discord
  uri: https://discord.gg/SFvbmKAxQZ

- platform: youtube
  username: greathorngames
  uri: https://www.youtube.com/@greathorngames

- platform: twitch
  username: greathorngames
  uri: https://www.twitch.tv/greathorngames

- platform: twitter
  username: greathorngames
  uri: https://x.com/greathorngames

- platform: github
  username: greathorngames
  uri: https://github.com/greathorngames

- platform: steam
  username: greathorngames
  uri: 

